### ISSUE TITLE
plot not working

### ISSUE THREAD

**Issue by miquael** [micahstubbs/roomscale-scatter#11]
frame and text renders fine, but no data is plotted (in Chrome version 49.0.2623.112 (64-bit))

from browser console:

```
d3.min.js:6 XMLHttpRequest cannot load file:///Users/mac/_DEV/_LAB/CogSpaceVR/roomscale-scatter/06/iris.csv. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
```

```
aframe-scatter-component.js:152 Uncaught TypeError: Cannot read property 'map' of null
```

```
WebGL: too many errors, no more errors will be reported to the console for this context.
```

**Comment by micahstubbs** [comment]
ah,  so several things happening here.  first you want to run a local server,  to avoid the CORS error

**Comment by micahstubbs** [comment]
this is my favorite local server 	`http-server` https://github.com/indexzero/http-server/blob/master/README.md

**Comment by micahstubbs** [comment]
`python -m SimpleHTTPServer 8888 &`
is another way to spin up a local server 
details and background knowledge here:
http://chimera.labs.oreilly.com/books/1230000000345/ch04.html#_terminal_with_python

**Comment by miquael** [comment]
thanks!  i'll try this out!

http://horizon.io may be a good server option too

**Comment by micahstubbs** [comment]
running a local server solved the issue ☺
